import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <div className="absolute bg-pink-200 w-[400px] h-[400px] rounded-full blur-3xl  border-[10px] border-blue-500 -z-10 left-6"></div>
        <div className="absolute hidden md:block bg-pink-200 w-[400px] h-[400px] rounded-full blur-3xl border-[10px] border-blue-500  bottom-0 right-0 -z-10"></div>
        <Navbar/>
        
        {children}
        
        
        </body>
    </html>
  );
}
